kubernetes:
  host: https://kubernetes.default
namespace: spotifyrandomalbum
pullPolicy: IfNotPresent
title: spotifyrandomalbum
replicas: 0
baseurl: spotify.hosrasmus.hopto.org
image:
  repository: docker.io/stefanmich/spotifyrandomalbum
  tag: "37@sha256:24aed374f9c97ff62b8ee3e1d84ee1230c22982bf32798b063214d79e3381977"
spotipyconfig:
  clientid: "clientid"
  clientsecret: "clientsecret"
  redirecturi: "redirecturi"
djangoconfig:
  allowedhosts: "spotify.hosrasmus.hopto.org"
  trustedorigins: ""
