kubernetes:
  host: https://kubernetes.default
namespace: spotifyrandomalbum
pullPolicy: IfNotPresent
title: spotifyrandomalbum
replicas: 0
baseurl: spotify.hosrasmus.hopto.org
image:
  repository: docker.io/stefanmich/spotifyrandomalbum
  tag: "38@sha256:d4d701a69e2dc9608c18c2e30439f3cdbc32690112fad304f9df37c0066e98a8"
spotipyconfig:
  clientid: "clientid"
  clientsecret: "clientsecret"
  redirecturi: "redirecturi"
djangoconfig:
  allowedhosts: "spotify.hosrasmus.hopto.org"
  trustedorigins: ""
