baseurl: cake.hosrasmus.hopto.org
image:
  repository: rasmus256docker/cakeotron
  tag: 288@sha256:bfdef47b85fa36a2679b33d5adb7b41767086b15ccc6ae9c8e74e570d923716c
dateserviceImage:
  repository: rasmus256docker/cakeotron-dateservice
  tag: 287@sha256:ca895fe2a17fb9c26e34b12006bdec62a529cbe0cad123b35af6df3af4b0eade
