baseurl: cake.hosrasmus.hopto.org
image:
  repository: rasmus256docker/cakeotron
  tag: 286@sha256:42018a7efa8370084eace33e87ae1bb87f1ff8bdc948a92ff437cd0df161c129
dateserviceImage:
  repository: rasmus256docker/cakeotron-dateservice
  tag: 286@sha256:dba7c8008234e09181e7f794e9591fbf9ae19822fd963332ac2362d14ca1c870
