baseurl: cake.hosrasmus.hopto.org
image:
  repository: rasmus256docker/cakeotron
  tag: 280@sha256:5127cca0202eac0ec1c7ef1bb49bb02d7377a3700444077efe61f9094d75653d
dateserviceImage:
  repository: rasmus256docker/cakeotron-dateservice
  tag: 279@sha256:963043d6a04f262d380a94e47597cab9493d09d6e9e75668f35628b8196678d2
