baseurl: cake.hosrasmus.hopto.org
image:
  repository: rasmus256docker/cakeotron
  tag: 272@sha256:b3ae53a6e35bb1605481a9cfd563b41b10bec092182d9ca898d85b87648392bb
dateserviceImage:
  repository: rasmus256docker/cakeotron-dateservice
  tag: 272@sha256:6dda9ee5bc9a7cfab95d4abb6e4485c76b35b9240595c45a6fcd061b623a4c4c
