baseurl: cake.hosrasmus.hopto.org
image:
  repository: rasmus256docker/cakeotron
  tag: 297@sha256:74ac11a55195c9d6f85843d42fb3d1549ce38e3f3838c9b134cdc0630de3b935
dateserviceImage:
  repository: rasmus256docker/cakeotron-dateservice
  tag: 297@sha256:e8ee531a40087e53935e399c0b214f7b7aff749f9478514e85f0818606e2d426
