baseurl: cake.hosrasmus.hopto.org
image:
  repository: rasmus256docker/cakeotron
  tag: 267@sha256:1ee5e6d65574b9496219249bb2c24974d35a6407225fe2979a2bcdb945f47e32
dateserviceImage:
  repository: rasmus256docker/cakeotron-dateservice
  tag: 267@sha256:07634aff131558544a693cfbd37ce66db41910a6c7adf1bb2e8c3a0b6c27b3a8
