kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
numNodes: 2003
blacklistedEdges: "0,0;1,1"
title: DDOExplorer
canaryweight: 0
baseurl: ddoexplorer.hosrasmus.hopto.org
image:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
canaryimage:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
uiimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251103.1943@sha256:045136e5730d6c777bbb3f7fee5afd5072eb2dd950efe674611a8b8d370181ff"
uicanaryimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251103.1943"
