kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
numNodes: 2003
blacklistedEdges: "0,0;1,1"
title: DDOExplorer
canaryweight: 0
baseurl: ddoexplorer.hosrasmus.hopto.org
image:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
canaryimage:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
uiimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251203.0238@sha256:8939504b8aa56726a1dd7fee011ca011e8cb08af8e3e8c9713b1045452bd825b"
uicanaryimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251203.0238"
