kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
numNodes: 2003
blacklistedEdges: "0,0;1,1"
title: DDOExplorer
canaryweight: 0
baseurl: ddoexplorer.hosrasmus.hopto.org
image:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
canaryimage:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
uiimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251205.1010@sha256:1ffaacac421f1b291393a791723ae2ec7554587fa302a08d90a32e1eef4527d0"
uicanaryimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251205.1010"
