kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
numNodes: 2003
blacklistedEdges: "0,0;1,1"
title: DDOExplorer
canaryweight: 0
baseurl: ddoexplorer.hosrasmus.hopto.org
image:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
canaryimage:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
uiimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251203.2102@sha256:c83219097e73905c7f771a43e17a5e9881ae15894ff06ed2dfd1bb794977c681"
uicanaryimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251203.2102"
