kubernetes:
  host: https://kubernetes.default
namespace: default
pullPolicy: IfNotPresent
numNodes: 2003
blacklistedEdges: "0,0;1,1"
title: DDOExplorer
canaryweight: 0
baseurl: ddoexplorer.hosrasmus.hopto.org
image:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
canaryimage:
  repository: rasmus256docker/ddoexplorer-api
  tag: "250217-1050"
uiimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251118.0750@sha256:3191a3bfaa85b96dc7c0d46ca0ef7a2a2c810f73c69734ef68046030bf0e8461"
uicanaryimage:
  repository: rasmus256docker/ddoexplorer-ui
  tag: "251118.0750"
